image: ubuntu

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

configuration:
  - Release
  
before_build:
  - cd .\build\workspaces\
  - update-workspaces.bat
  - cd ..\..\

build:
  project: .\build\workspaces\vc2015\pyrogenesis.sln
  parallel: true
  verbosity: quiet

after_build:
  - 7z a binaries.7z .\binaries


artifacts:
- path: binaries.7z


deploy:
  provider: GitHub
  auth_token:
    secure: PiQDTyaNV3HdYRawTlwyD/bsMbpBg2Kx+/BEUEz9qOasvZlDBmxj3tFB0bNYwXIc
  artifact: binaries.7z
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
